const ADD_ARTICLE = "ADD_ARTICLE";

const ADDRESS_UPDATE = 'ADDRESS_UPDATE';

const USER_UPDATE = 'USER_UPDATE';

const TOKEN_UPDATE = 'TOKEN_UPDATE';

const CART_PRODUCT_INC = 'CART_PRODUCT_INC';
const CART_PRODUCT_DEC = 'CART_PRODUCT_DEC';
const CART_PRODUCT_REMOVE = 'CART_PRODUCT_REMOVE';
const CART_PRODUCT_ADD = 'CART_PRODUCT_ADD';
const CART_CAMPAIGN_REMOVE = 'CART_CAMPAIGN_REMOVE';
const CART_RESET = 'CART_RESET';


export {
    ADD_ARTICLE,
    ADDRESS_UPDATE,
    USER_UPDATE,
    TOKEN_UPDATE,
    CART_PRODUCT_INC,
    CART_PRODUCT_DEC,
    CART_PRODUCT_REMOVE,
    CART_PRODUCT_ADD,
    CART_CAMPAIGN_REMOVE,
    CART_RESET
}
